---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: e4k-repo
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://e4kpreview.azurecr.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: e4k-release
  namespace: flux-system
spec:
  releaseName: e4k
  targetNamespace: default
  chart:
    spec:
      chart: az-e4k
      sourceRef:
        kind: HelmRepository
        name: e4k-repo
      version: 0.3.0-rc2
  interval: 1m0s

apiVersion: az-edge.com/v1alpha1
kind: Broker
metadata:
  name: "my-broker"
  namespace: default
spec:
  mode: auto
  image:
    pullPolicy: Always
    repository: e4kpreview.azurecr.io/dmqtt-pod
    tag: 0.3.0-rc2
  authImage:
    pullPolicy: Always
    repository: e4kpreview.azurecr.io/dmqtt-authentication
    tag: 0.3.0-rc2
---
apiVersion: az-edge.com/v1alpha1
kind: BrokerListener
metadata:
  name: "my-non-tls-listener"
  namespace: default
spec:
  brokerRef: "my-broker"
  authenticationEnabled: false
  authorizationEnabled: false
  port: 1883
---
apiVersion: az-edge.com/v1alpha1
kind: BrokerDiagnostic
metadata:
  name: "my-diag"
  namespace: default
spec:
  brokerRef: "my-broker"
  diagnosticServiceEndpoint: azedge-diagnostics-service:9700
  enableMetrics: true  
  enableTracing: true  
  logLevel: debug,hyper=off,kube_client=off,tower=off,conhash=off,h2=off
  enableSelfCheck: false
